from typing import Protocol

from app.shared.domain.aggregate import AggregateRoot


class IUnitOfWork(Protocol):
    def __enter__(self) -> "IUnitOfWork": ...

    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...

    def flush(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def track_aggregate(self, aggregate: AggregateRoot) -> None: ...
